---
- name: Scan settings
  become: yes
  # become_user: postgres
  command: psql -U postgres -c "copy (select name, setting from pg_settings order by name) to stdout delimiter ';' csv;"
  register: command_output

  # command: psql -c "copy (select source, category, name, setting, vartype from pg_settings order by source, category, name) to stdout delimiter ';' csv header;"
- name: Save settings
  delegate_to: localhost
  copy:
    content: "{{command_output.stdout}}"
    dest: "roles/scan_dbparams/files/p5432_{{ ansible_hostname }}.txt"
